---
- hosts: all
  become: true

  pre_tasks:
    - name: 'Install packages by apt'
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.apt:
        state: present
        name: "{{ packages }}"
      vars:
        packages:
          - nginx
          - php-fpm

  tasks:
    - name: 'Copy files (j2)'
      become: true
      ansible.builtin.template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
      with_items:
        - { 'src':'files/eccube.nginx.j2', 'dest':'/etc/nginx/sites-available/eccube', 'mode':'0644', 'owner':'root', 'group':'root' }
      notify:
        - 'Reload nginx'

    - name: 'Symlink files'
      become: true
      ansible.builtin.file: src={{ item.src }} path={{ item.path }} state={{ item.state }}
      with_items:
        - { 'src':'../sites-available/eccube', 'path':'/etc/nginx/sites-enabled/eccube', 'state':'link' }
      notify:
        - 'Reload nginx'

    - name: 'Delete symlink'
      become: true
      ansible.builtin.file: path={{ item.path }} state={{ item.state }}
      with_items:
        - { 'path':'/etc/nginx/sites-enabled/default', 'state':'absent' }
      notify:
        - 'Reload nginx'

  handlers:
    - name: 'Reload nginx'
      become: true
      ansible.builtin.service:
        name: nginx.service
        state: reloaded
