---
- hosts: all
  become: true

  tasks:
    - name: "Set timezone to Asia/Tokyo"
      community.general.timezone:
        name: Asia/Tokyo

    - name: Update and upgrade apt packages
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 21600
        autoremove: true
        autoclean: true

    - name: "Install packages by apt"
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.apt:
        state: present
        name: "{{ packages }}"
      vars:
        packages:
          # - dstat
          # - nmap
          - python3-pip
          # - qemu-guest-agent

    # - name: 'Start and enable services'
    #   ansible.builtin.service: name={{ item }} state=started enabled=true
    #   with_items:
    #     - qemu-guest-agent
